name: Mend AI

on: workflow_dispatch

jobs:
  cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv --user
        pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
        pip install -r requirements.txt

    - name: Mend CLI Scan (Ubuntu)
        env:
          MEND_EMAIL: ${{secrets.MEND_EMAIL}}
          MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
          MEND_URL: https://saas.mend.io
        run: |
          echo Downloading Mend CLI
          curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
          echo run Mend scan
          mend dep -u
        
